#!/usr/bin/env sh
# capture.sh — regenerate the site's frames without VHS.
#
# Runs the real program in a PTY with the pinned config (media/demo.toml), one
# scene at a time, and converts each captured screen to a flat SVG in
# docs/assets/scenes/. Deterministic: same config, same page, same size.
#
# Usage: sh scripts/capture.sh            # WR=$PWD/wr by default
#        WR=/path/to/wr sh scripts/capture.sh
set -eu

root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$root"

WR=${WR:-"$root/wr"}
if [ ! -x "$WR" ]; then
  echo "capture: building wr"
  go build -o "$WR" .
fi

out=$(mktemp -d)
echo "capture: scenes -> $out/frames"
python3 scripts/pty_capture.py \
  --wr "$WR" \
  --config media/demo.toml \
  --page media/demo.html \
  --scene media/scenes.json \
  --out "$out" \
  --width 100 --height 30

mkdir -p docs/assets/scenes
python3 - "$out" <<'PY'
import json, subprocess, sys
from pathlib import Path

out = Path(sys.argv[1])
for s in json.loads(Path("media/scenes.json").read_text())["scenes"]:
    frame = out / "frames" / f"{s['name']}.ansi"
    if not frame.exists():
        continue
    subprocess.run([sys.executable, "scripts/ansi_to_svg.py", str(frame),
                   "--title", f"wr — {s['name']}",
                   "--out", f"docs/assets/scenes/{s['name']}.svg"], check=True)
PY

version=$("$WR" --version 2>/dev/null || echo unknown)
commit=$(git rev-parse --short HEAD 2>/dev/null || echo -)
{
  echo "# Recorded assets"
  echo
  echo "Generated by \`scripts/capture.sh\` from the same scenes as \`media/*.tape\`."
  echo
  echo "- wr version: \`$version\`"
  echo "- built from: \`$commit\`"
  echo "- date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "| file | bytes | sha256 |"
  echo "|---|---|---|"
  for f in docs/assets/scenes/*.svg; do
    [ -f "$f" ] || continue
    printf '| %s | %s | %s |\n' "$f" "$(wc -c <"$f")" "$(sha256sum "$f" | cut -c1-16)"
  done
} >media/ASSETS.md

echo "capture: done — $(ls docs/assets/scenes | tr '\n' ' ')"
echo "manifest: media/ASSETS.md ($version)"
