#!/usr/bin/env sh
# record.sh — regenerate every GIF with VHS (https://github.com/charmbracelet/vhs).
#
# VHS drives a real terminal, so the tapes also capture the frames the site uses
# (docs/assets/scenes) through scripts/capture.sh. Requires: vhs, ffmpeg.
#
# Usage: sh scripts/record.sh [tape...]     # default: all tapes in media/
set -eu

root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$root"

if ! command -v vhs >/dev/null 2>&1; then
  echo "record: vhs is not installed" >&2
  echo "  go install github.com/charmbracelet/vhs@latest   (also needs ffmpeg)" >&2
  echo "  or regenerate the SVG frames without VHS: sh scripts/capture.sh" >&2
  exit 1
fi
command -v ffmpeg >/dev/null 2>&1 || { echo "record: ffmpeg is missing" >&2; exit 1; }

mkdir -p media/out
cd media
tapes="$*"
[ -n "$tapes" ] || tapes="ui links sections shortcuts search"

version=$("$root/../wr" --version 2>/dev/null || echo unknown)
[ -x "$root/wr" ] || go build -o "$root/wr" "$root" || true

for t in $tapes; do
  echo "record: $t.tape -> media/out/$t.gif"
  vhs "$t.tape"
done

version=$("$root/wr" --version 2>/dev/null || echo unknown)
commit=$(git rev-parse --short HEAD 2>/dev/null || echo -)
{
  echo "# Recorded assets (VHS)"
  echo
  echo "Generated by \`scripts/record.sh\` with VHS; every tape pins the same"
  echo "config (media/demo.toml) and page (media/demo.html)."
  echo
  echo "- wr version: \`$version\`"
  echo "- built from: \`$commit\`"
  echo "- date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "| gif | bytes | sha256 |"
  echo "|---|---|---|"
  for f in out/*.gif; do
    [ -f "$f" ] || continue
    printf '| %s | %s | %s |\n' "$f" "$(wc -c <"$f")" "$(sha256sum "$f" | cut -c1-16)"
  done
} >media/ASSETS.md
echo "record: done — $(ls out | tr '\n' ' ')"
